# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

variant_seed_search_terms = [

]

# "Bulbasaur",
# "Ivysaur",
# "Venusaur"
# "Charmander",
# "Charmeleon",
# "Charizard",
# "Squirtle",
# "Wartortle", 
# "Blastoise",
# "Caterpie",
# "Metapod",
# "Butterfree"
# "Weedle",
# "Kakuna",
# "Beedrill",
# "Pidgey",
# "Pidgeotto",
# "Pidgeot,"
# "Rattata",
# "Raticate",
# "Spearow",
# "Fearow",
# "Ekans",
# "Arbok",
# "Pikachu",
# "Raichu",
# "Sandshrew",
# "Sandslash",
# "Nidoran",
# "Nidorina",
# "Nidoqueen",
# "Nidorino",
# "Nidoking",
# "Clefairy",
# "Clefable",
# "Vulpix",
# "Ninetales,"
# "Jigglypuff",
# "Wigglytuff",
# "Zubat",
# "Golbat",
# "Oddish",
# "Gloom",
# "Vileplume",
# "Paras",
# "Parasect",
# "Venonat",
# "Venomoth",
# "Diglett",
# "Dugtrio",
# "Meowth",
# "Persian",
# "Psyduck",
# "Golduck",
# "Mankey",
# "Primeape",
# "Growlithe",
# "Arcanine",
# "Poliwag",
# "Poliwhirl",
# "Poliwrath",
# "Abra",
# "Kadabra",
# "Alakazam",
# "Machop",
# "Machoke",
# "Machamp",
# "Bellsprout",
# "Weepinbell",
# "Victreebel",

# "Tentacool",
# "Tentacruel",
# "Geodude",
# "Graveler",
# "Golem",
# "Ponyta",
# "Rapidash",
# "Slowpoke",
# "Slowbro",
# "Magnemite",
# "Farfetch'd",
# "Doduo",
# "Dodrio",
# "Seel",
# "Dewgong",
# "Grimer",
# "Muk",
# "Shellder",
# "Cloyster",
# "Gastly",
# "Haunter",
# "Gengar",
# "Onix",
# "Drowzee",
# "Hypno",
# "Krabby",
# "Kingler",
# "Voltorb",
# "Electrode",
# "Exeggcute",
# "Exeggcutor",
# "Cubone",
# "Marowak",
# "Hitmonlee",
# "Hitmonchan",
# "Lickitung",
# "Koffing",
# "Weezing",
# "Rhyhorn",
# "Rhydon",
# "Chansey",
# "Tangela",
# "Kangaskhan",
# "Horsea",
# "Seadra",
# "Goldeen",
# "Seaking",
# "Staryu",
# "Starmie",
# "Mr. Mime",
# "Scyther",
# "Jynx",
# "Electabuzz",
# "Magmar",
# "Pinsir",
# "Tauros",
# "Magikarp",
# "Gyarados",
# "Lapras",
# "Ditto",
# "Eevee",
# "Vaporeon",
# "Jolteon",
# "Flareon",
# "Porygon",
# "Omanyte",
# "Omastar",
# "Kabuto",
# "Kabutops",
# "Aerodactyl",
# "Snorlax",
# "Articuno",
# "Zapdos",
# "Moltres",
# "Dratini",
# "Dragonair",
# "Dragonite",
# "Mewtwo",
# "Mew",

variant_seed_search_terms.each do |search_term|
    VariantsFacade.create_variants_by_search_term(search_term)
end